deployment:
  tasks:
    # clear old files
    - echo "Clearing public_html…"  
    - rm -rf ../public_html/*

    # copy new ones
    - echo "Copying out → public_html…"  
    - cp -R out/* ../public_html/

    - echo "Deployment complete."
